// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_intersecting_voxels
NumericVector find_intersecting_voxels(NumericVector xyz_begin, NumericVector xyz_end);
RcppExport SEXP _MoDVE_find_intersecting_voxels(SEXP xyz_beginSEXP, SEXP xyz_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xyz_begin(xyz_beginSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xyz_end(xyz_endSEXP);
    rcpp_result_gen = Rcpp::wrap(find_intersecting_voxels(xyz_begin, xyz_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MoDVE_find_intersecting_voxels", (DL_FUNC) &_MoDVE_find_intersecting_voxels, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MoDVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
