# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find all the voxels that a segment intersects in 3D space
#'
#' @param xyz_begin a numeric vector of length 3 with the x-y-z coordinates
#' of the start point of the segment
#' @param xyz_end a numeric vector of length 3 with the x-y-z coordinates
#' of the end point of the segment
#'
#' @returns a list of length 3 integer vectors, the 3D coordinates of all voxels
#' intersected by the segment
#'
NULL

find_intersecting_voxels <- function(xyz_begin, xyz_end) {
    .Call('_MoDVE_find_intersecting_voxels', PACKAGE = 'MoDVE', xyz_begin, xyz_end)
}

