# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_intersecting_voxels <- function(coords_begin, coords_end) {
    .Call('_MoDVE_find_intersecting_voxels', PACKAGE = 'MoDVE', coords_begin, coords_end)
}

