name: Test R scripts

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  setup-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("optparse", repos="http://cran.uk.r-project.org")'
          Rscript -e 'install.packages("configr", repos="http://cran.uk.r-project.org")'
          Rscript -e 'install.packages("foreach", repos="http://cran.uk.r-project.org")'

      - name: Run and test A1 script
        run: |
          cd ${{ github.workspace }}
          cd R/
          Rscript A1.R -i tests/config_a1.toml
          Rscript tests/test_a1.R

      - name: Run and test A2 script
        run: |
          cd ${{ github.workspace }}
          cd R/
          Rscript A2.R -i tests/config_a2.toml
          Rscript tests/test_a2.R

      - name: Run and test A3 script
        run: |
          cd ${{ github.workspace }}
          cd R/
          Rscript A3.R -i tests/config_a3.toml
          Rscript tests/test_a3.R

      - name: Run and test A4 script
        run: |
          cd ${{ github.workspace }}
          cd R/
          Rscript A4.R -i tests/config_a4.toml
          Rscript tests/test_a4.R
